### ISSUE TITLE
[bug report] 連點會壞掉

### ISSUE THREAD

**Issue by Anthony-Wang-Taiwan** [ChenKB91/pygame_wuzhichi#1]
Reproduce: 用local開3個terminal, 一個跑server_main.py，剩下兩個各跑一個client_main.py，黑棋先手時在某一格按兩下，換白棋下一手，再換黑棋時就會壞掉了

Error message:
something goes wrong when receiving game status from the server.
Traceback (most recent call last):
  File "client_main.py", line 167, in <module>
    if player.receive_game_status() == "End_Game":
  File "client_main.py", line 102, in receive_game_status
    return received_game_status
UnboundLocalError: local variable 'received_game_status' referenced before assignment

**Comment by Anthony-Wang-Taiwan** [comment]
在client_main裡面，在換那個user下棋之前把pygame 的event list清空就可以了
